# Generated by Django 6.0.3 on 2026-03-19 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('passed', models.IntegerField()),
                ('failed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='users.testsuite')),
            ],
        ),
    ]
